from unicodedata import name
from .import views 
from .forms import *
from django.urls import path,include
from django.contrib.auth.views import PasswordResetView , PasswordResetDoneView , PasswordResetConfirmView , PasswordResetCompleteView
urlpatterns = [

    path('', views.home , name="home"),
    path("tag/<slug:tag_slug>/" , views.product_list_tags , name="product_list2"), 
    path("category/<slug:category_slug>/" , views.product_list_category , name="product_list3"), 
    path('search/', views.search , name="search"),
    path('product_list/', views.product_list , name="product_list"),
    path('category/<int:id>/<slug:slug>/', views.category_products , name="category_products"),
    path('brand_product_list/<int:brand_id>' , views.brand_product_list , name = "brand_product_list"),
    path('product_detail/<str:slug>/<int:id>' , views.product_detail , name = "product_detail"),
    path('filter-data/' , views.filter_data , name = "filter_data"),
    path('load-more-data/' , views.load_more_data , name = "load_more_data"),
    path('cart/' , views.cart_list , name = "cart"),
    #path('deleteformcart/<int:id>' , views.deleteformcart , name = "deleteformcart"),
    path('update-cart' , views.update_cart_item , name = "update_cart"),
    path('signup/' , views.signup , name = "signup"),
    path('order-product/' , views.order_product , name = "order_product"),
    path('save-review/<int:pid>' , views.save_review , name="save_review"),
    path('dashboard/' , views.my_dashboard , name= "my_dashboard"),
    path('my-orders/' , views.my_orders , name= "my_orders"),
    path('my-orders-items/<int:id>',views.my_order_items, name='my_order_items'),
    path('add-wishlist/' , views.add_wishlist , name= "add_wishlist"),
    path('wishlist/' , views.wishlist , name= "wishlist"),
    path('my-review/' , views.my_review , name= "my_review"),
    path('my-address/' , views.my_address , name= "my_address"),
    path('save-address/' , views.save_address , name= "save_address"),
    path('activate-address/' , views.activate_address , name= "activate_address"),
    path('update-address/<int:id>' , views.update_address , name= "update_address"),
    path('edit-profile/' , views.Edit_Profile , name= "Edit_Profile"),
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('notifs/', views.notifs, name='notifs'),
    path('get_notifs',views.get_notifs,name='get_notifs'),
    path('mark_read_notif',views.mark_read_notif,name='mark_read_notif'),
    path('api/<int:id>' , views.link , name='api-link'),
    path('api/<int:id>/like' , views.like , name='api-like'),
    path('api/<int:id>/dislike' , views.dislike , name='api-dislike'),
    path('update_cart/<int:id>' , views.update_cart , name= "update_cart"),
    path('deletereview/<int:id>' , views.deletereview , name = "deletereview"),
    path("forgotpass/",views.forgotpass, name="forgotpass"),
    path("reset_password/",views.reset_password,name="reset_password"),
    path(r'^books/(?P<id>\d+)/update$', views.book_update, name='book_update'),
    path(r'^books/(?P<id>\d+)/delete$', views.book_delete, name='book_delete'),
    path(r'^wishlist/(?P<id>\d+)/delete$', views.wishlist_delete, name='wishlist_delete'),
    path(r'^books1/(?P<id>\d+)/delete2$', views.book2_delete, name='delete_cart_home'),
    path('blog_list/' , views.blog_list , name = "blog_list"),
    path('blog_detail/<int:id>' , views.blog_details , name = "blog_detail"),
    path('save-comment/<int:pid>' , views.save_comment , name="save_comment"),
    path('notfound/' , views.notfound , name="notfound"),
    path('tamas/' , views.contact_us , name="tamas"),
    

]
