# Generated by Django 4.0.2 on 2022-03-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_product_image_productattribute_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس الکترونیکی')),
                ('national_code', models.IntegerField(verbose_name='کد ملی')),
                ('name_of_receiver', models.CharField(max_length=100, verbose_name='نام تحویل گیرنده')),
                ('phone_number', models.IntegerField(verbose_name='شماره همراه')),
                ('postal_address', models.CharField(max_length=200, verbose_name='آدرس پستی')),
                ('postal_code', models.CharField(max_length=50, verbose_name='کد پستی')),
                ('city', models.CharField(max_length=100, verbose_name='استان')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
            ],
        ),
    ]
