# Generated by Django 4.0.2 on 2022-03-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
