# Generated by Django 4.0.2 on 2022-03-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_cartorderitems_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='image',
        ),
    ]
