# Generated by Django 4.0.2 on 2022-03-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_cartorderitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_rating',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=150, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_text',
            field=models.TextField(verbose_name='متن دیدگاه'),
        ),
    ]
