# Generated by Django 4.0.2 on 2022-03-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_useraddressbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressbook',
            name='address',
            field=models.TextField(verbose_name='آدرس محل سکونت'),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='mobile',
            field=models.CharField(max_length=50, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
    ]
