# Generated by Django 4.0.2 on 2022-04-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_productattribute_image_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='image_id',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(default=None, upload_to='product_imgs/'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
