# Generated by Django 4.0.2 on 2022-04-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='image',
        ),
    ]
