# Generated by Django 4.0.2 on 2022-04-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_order_orderproduct_remove_cartorderitems_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variant',
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/users/'),
        ),
    ]
