# Generated by Django 4.0.2 on 2022-04-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_orderproduct_variant_useraddressbook_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressbook',
            name='phone_2',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='postal_code',
            field=models.IntegerField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='tag',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddressbook',
            name='vahed',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
