# Generated by Django 4.0.2 on 2022-04-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_order_phone_2_order_postal_code_order_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
