# Generated by Django 4.0.2 on 2022-04-17 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0049_alter_productattribute_title_notifuserstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL, verbose_name='نپسندیدن'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='پسندیدن'),
        ),
    ]
