# Generated by Django 4.0.2 on 2022-04-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_productreview_dislikes_productreview_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review_rating',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=150, verbose_name='امتیاز'),
        ),
    ]
