# Generated by Django 4.0.2 on 2022-04-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_productreview_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressbook',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/users/'),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='phone_2',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='postal_code',
            field=models.IntegerField(max_length=150),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='tag',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='vahed',
            field=models.IntegerField(max_length=20),
        ),
    ]
