# Generated by Django 4.0.2 on 2022-04-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_useraddressbook_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressbook',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس محل سکونت'),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='phone_2',
            field=models.IntegerField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='postal_code',
            field=models.IntegerField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='status',
            field=models.BooleanField(blank=True, default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='tag',
            field=models.IntegerField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='vahed',
            field=models.IntegerField(blank=True, max_length=20),
        ),
    ]
