# Generated by Django 4.0.2 on 2022-04-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_useraddressbook_phone_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressbook',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس محل سکونت'),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/'),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='postal_code',
            field=models.IntegerField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='tag',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useraddressbook',
            name='vahed',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
