# Generated by Django 4.0.2 on 2022-05-23 14:32

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('main', '0063_product_tags_alter_shopcart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descriptions', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='blog_images/')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'بنر محصولات'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برند'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ بندی', 'verbose_name_plural': 'رنگ بندی '},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'عکس محصول', 'verbose_name_plural': 'عکس محصولات'},
        ),
        migrations.AlterModelOptions(
            name='notifuserstatus',
            options={'verbose_name': 'وضعیت بازدید از اعلانات', 'verbose_name_plural': 'وضعیت اعلانات'},
        ),
        migrations.AlterModelOptions(
            name='notify',
            options={'verbose_name': 'اعلانات', 'verbose_name_plural': 'اعلانات'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارشات کاربر', 'verbose_name_plural': 'سفارشات کاربران'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'سفارشات محصول', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'ویژگی محصولات', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'دیدگاه کاربر', 'verbose_name_plural': 'دیدگاه کاربران'},
        ),
        migrations.AlterModelOptions(
            name='shopcart',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد خرید محصولات'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'سایر بندی', 'verbose_name_plural': 'سایز بندی '},
        ),
        migrations.AlterModelOptions(
            name='useraddressbook',
            options={'verbose_name': 'دفترچه آدرس کاربران', 'verbose_name_plural': 'دفترچه آدرس'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'لیست علاقه مندی کاربران', 'verbose_name_plural': 'علاقه مندی ها'},
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='موجودی محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand', verbose_name='برند محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(verbose_name='جزییات محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(default=0, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_imgs/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='تایید محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(max_length=255, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='minamount',
            field=models.IntegerField(default=3, verbose_name='حداقال موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='آدرس محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.TextField(verbose_name='مشخصات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Size', 'Size'), ('Color', 'Color'), ('Size-Color', 'Size-Color')], default='None', max_length=10, verbose_name='ویژگی های محصول'),
        ),
    ]
