# Generated by Django 4.0.2 on 2022-05-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_blog_category_blog_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='category_blog',
            options={'verbose_name': 'دسته بندی مقاله', 'verbose_name_plural': 'دسته بندی مقالات'},
        ),
    ]
