# Generated by Django 4.0.2 on 2022-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=2004, max_length=254, verbose_name='آدرس الکترونیکی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='family',
            field=models.CharField(default=2004, max_length=300, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=2004, max_length=300, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرسش'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', verbose_name='متن پرسش'),
        ),
    ]
