# Generated by Django 4.0.2 on 2022-05-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_comment_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product',
        ),
    ]
