# Generated by Django 4.0.2 on 2022-06-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_comment_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
