# Generated by Django 4.0.2 on 2022-06-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='خرید این محصول را توصیه می\u200cکنم'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='آدرس الکترونیکی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='family',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت نمایش'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text_comment',
            field=models.TextField(verbose_name='متن پرسش'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
    ]
