# Generated by Django 4.0.2 on 2022-06-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_productreview_recommend_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='recommend',
            field=models.CharField(choices=[('خرید این محصول را توصیه می\u200cکنم', 'خرید این محصول را توصیه می\u200cکنم'), ('خرید این محصول را توصیه نمیکنم', 'خرید این محصول را توصیه نمیکنم')], max_length=150, verbose_name='توصیه خرید محصول'),
        ),
    ]
