# Generated by Django 4.0.2 on 2022-06-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_remove_commentblog_product_commentblog_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.commentblog', verbose_name='پاسخ به نظر'),
        ),
    ]
