# Generated by Django 4.0.2 on 2022-06-17 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_commentblog_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentblog',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.commentblog'),
        ),
    ]
