# Generated by Django 4.0.2 on 2022-09-01 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_product_date_of_made_product_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentblog',
            options={'verbose_name': 'نظرات مقاله', 'verbose_name_plural': 'نظرات مقالات'},
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='size',
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blog', verbose_name='مقاله'),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج نظر'),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام کاربر'),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='main.commentblog', verbose_name='پاسخ به نظر'),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='text',
            field=models.TextField(max_length=10000, verbose_name='متن نظر'),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان نظر'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
