# Generated by Django 4.0.2 on 2022-09-03 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slug', models.CharField(max_length=200, verbose_name='آدرس دسته بندی')),
                ('status', models.BooleanField(verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی محصولات',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='دسته بندی'),
        ),
    ]
