# Generated by Django 4.0.2 on 2022-09-03 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0083_category_product_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_product',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category_product', verbose_name='زیر دست'),
        ),
        migrations.AddField(
            model_name='category_product',
            name='position',
            field=models.IntegerField(null=True, verbose_name='پوزیشن'),
        ),
        migrations.AlterField(
            model_name='category_product',
            name='status',
            field=models.BooleanField(verbose_name='آیا نمایش داده شود؟'),
        ),
    ]
